# Правила статического анализа для серверной части.
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
